### PR TITLE
Fix sqsgenerator version bump

### LINKED ISSUE #564: CI Notebooks broken
Right now two notebooks break: SQS and tests_sphinx_sphinx_check_all (tracebacks below).

I am not sure where this comes from. I saw that sqs had recent release (yesterday on conda) and 
https://github.com/dgehringer/sqsgenerator/releases/tag/v0.1 which is probably related. 

```
Input Notebook:  notebooks/sqs.ipynb
Output Notebook: notebooks/sqs-out.ipynb

Executing:   0%|          | 0/9 [00:00<?, ?cell/s]Executing notebook with kernel: python3

Executing:  11%|█         | 1/9 [00:03<00:31,  3.90s/cell]
Executing:  44%|████▍     | 4/9 [00:04<00:04,  1.03cell/s]
Executing:  44%|████▍     | 4/9 [00:05<00:07,  1.45s/cell]
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/papermill/cli.py", line [250](https://github.com/pyiron/pyiron_atomistics/runs/5567082128?check_suite_focus=true#step:6:250), in papermill
    execute_notebook(
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [4], in <cell line: 6>()
      4 job.input['iterations'] = 1e6
      5 job.server.cores = 2
----> 6 job.run()

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args, **kwargs)

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py:704, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    702     self._run_if_repair()
    703 elif status == "initialized":
--> 704     self._run_if_new(debug=debug)
    705 elif status == "created":
    706     self._run_if_created()

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py:1418, in GenericJob._run_if_new(self, debug)
   1416 else:
   1417     self.save()
-> 1418     self.run()

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args, **kwargs)

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py:706, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    704     self._run_if_new(debug=debug)
    705 elif status == "created":
--> 706     self._run_if_created()
    707 elif status == "submitted":
    708     self._run_if_submitted()

File /usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py:1437, in GenericJob._run_if_created(self)
   1435     self.run_if_manually(_manually_print=False)
   1436 elif self.server.run_mode.modal:
-> 1437     self.run_static()
   1438 elif (
   1439     self.server.run_mode.non_modal
   1440     or self.server.run_mode.thread
   1441     or self.server.run_mode.worker
   1442 ):
   1443     self.run_if_non_modal()

File ~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/sqs.py:204, in SQSJob.run_static(self)
    203 def run_static(self):
--> 204     self._lst_of_struct, decmp, iterations, cycle_time = get_sqs_structures(
    205         structure=self.structure,
    206         mole_fractions={k: v for k, v in self.input.mole_fractions.items()},
    207         weights=self.input.weights,
    208         objective=self.input.objective,
    209         iterations=self.input.iterations,
    210         output_structures=self.input.n_output_structures,
    211         num_threads=self.server.cores,
    212     )
    213     for i, structure in enumerate(self._lst_of_struct):
    214         with self.project_hdf5.open("output/structures/structure_" + str(i)) as h5:

File ~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/sqs.py:62, in get_sqs_structures(structure, mole_fractions, weights, objective, iterations, output_structures, num_threads)
     59 if not num_threads:
     60     # Thats default behaviour
     61     num_threads = cpu_count()
---> 62 iterator = ParallelSqsIterator(
     63     structure, mole_fractions, weights, num_threads=num_threads
     64 )
     65 structures, decmp, iter_, cycle_time = iterator.iteration(
     66     iterations=iterations, output_structures=output_structures, objective=objective
     67 )
     68 return [pymatgen_to_pyiron(s) for s in structures], decmp, iter_, cycle_time

NameError: name 'ParallelSqsIterator' is not defined
```
```
Input Notebook:  notebooks/tests_sphinx_sphinx_check_all.ipynb
Output Notebook: notebooks/tests_sphinx_sphinx_check_all-out.ipynb

Executing:   0%|          | 0/33 [00:00<?, ?cell/s]Executing notebook with kernel: python3

Executing:   3%|▎         | 1/33 [00:03<02:05,  3.93s/cell]
Executing:  12%|█▏        | 4/33 [00:09<01:02,  2.14s/cell]
Executing:  15%|█▌        | 5/33 [00:09<00:44,  1.57s/cell]
Executing:  18%|█▊        | 6/33 [00:09<00:31,  1.16s/cell]
Executing:  24%|██▍       | 8/33 [00:09<00:17,  1.47cell/s]
Executing:  30%|███       | 10/33 [00:09<00:10,  2.20cell/s]
Executing:  33%|███▎      | 11/33 [00:17<00:45,  2.09s/cell]
Executing:  36%|███▋      | 12/33 [00:18<00:38,  1.83s/cell]
Executing:  39%|███▉      | 13/33 [00:45<02:45,  8.27s/cell]
Executing:  42%|████▏     | 14/33 [00:45<01:55,  6.10s/cell]
Executing:  45%|████▌     | 15/33 [00:51<01:47,  5.98s/cell]
Executing:  48%|████▊     | 16/33 [00:59<01:51,  6.54s/cell]
Executing:  55%|█████▍    | 18/33 [01:00<00:58,  3.89s/cell]
Executing:  58%|█████▊    | 19/33 [01:13<01:23,  5.97s/cell]
Executing:  61%|██████    | 20/33 [01:13<00:58,  4.46s/cell]
Executing:  64%|██████▎   | 21/33 [01:18<00:55,  4.66s/cell]
Executing:  67%|██████▋   | 22/33 [01:24<00:53,  4.88s/cell]
Executing:  70%|██████▉   | 23/33 [01:36<01:09,  6.90s/cell]
Executing:  73%|███████▎  | 24/33 [01:36<00:44,  4.94s/cell]
Executing:  76%|███████▌  | 25/33 [01:41<00:41,  5.16s/cell]
Executing:  79%|███████▉  | 26/33 [01:47<00:37,  5.31s/cell]
Executing:  82%|████████▏ | 27/33 [02:09<01:01, 10.30s/cell]
Executing:  85%|████████▍ | 28/33 [02:15<00:45,  9.07s/cell]
Executing:  88%|████████▊ | 29/33 [02:16<00:25,  6.40s/cell]
Executing:  91%|█████████ | 30/33 [02:31<00:27,  9.24s/cell]
Executing:  97%|█████████▋| 32/33 [02:32<00:05,  5.05s/cell]Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/database/generic.py", line 994, in get_item_by_id
    return self.__get_items("id", int(item_id))[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda/envs/test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 677, in start
    self.io_loop.start()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/usr/share/miniconda/envs/test/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/usr/share/miniconda/envs/test/lib/python3.10/asyncio/base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/share/miniconda/envs/test/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py", line 1375, in signal_intercept
    self.drop_status_to_aborted()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py", line 1383, in drop_status_to_aborted
    self.refresh_job_status()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/job/generic.py", line [435](https://github.com/pyiron/pyiron_atomistics/runs/5567082128?check_suite_focus=true#step:6:435), in refresh_job_status
    initial_status=self.project.db.get_job_status(self.job_id),
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/database/generic.py", line 1122, in get_job_status
    return self.get_item_by_id(item_id=job_id)["status"]
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/pyiron_base/database/generic.py", line 1001, in get_item_by_id
    raise IndexError(
IndexError: ('Error when trying to find elements by given Job ID: ', IndexError('list index out of range'))
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1200, in _at_shutdown
    await self._progressively_terminate_all_children()
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 297, in process_control
    await result
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 836, in shutdown_request
    await self._at_shutdown()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1206, in _at_shutdown
    self.session.send(
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/jupyter_client/session.py", line 853, in send
    stream.send_multipart(to_send, copy=copy)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/iostream.py", line 285, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/iostream.py", line 225, in send_multipart
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/iostream.py", line 218, in schedule
    f()
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/iostream.py", line 225, in <lambda>
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/ipykernel/iostream.py", line 233, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'send_multipart'
```

### PR DESCRIPTION
**Pull request by dgehringer**
Fixes `SQSJob` to work with both versions *v0.0.5* and *v0.1*. 
- left HDF format and input parameters untouched -> backwards compatibilty
- deprecation warning whe importing  *v0.0.5*
- CI notebook [sqs.ipynb](https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/sqs.ipynb) runs with both versions ( *v0.0.5* and *v0.1*)
- improved input validation -> warnings if composition is changes
- new features of *v0.1* are not included  -> backwards compatibilty

Fixes #564

### CODE REVIEW

**Comment by jan-janssen** [comment]
The coverage fails to push the test statistics - but I guess that is a general issue with forks

**Comment by jan-janssen** [comment]
The backwards compatibility to 0.0.5 seems to be broken:
```
File ~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/sqs.py:354, in SQSJob.run_static(self)
[340](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:340)
    353 def run_static(self):
[341](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:341)
--> 354     self._lst_of_struct, decmp, iterations, cycle_time = get_sqs_structures(
[342](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:342)
    355         structure=self.structure,
[343](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:343)
    356         mole_fractions={k: v for k, v in self.input.mole_fractions.items()},
[344](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:344)
    357         weights=self.input.weights,
[345](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:345)
    358         objective=self.input.objective,
[346](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:346)
    359         iterations=self.input.iterations,
[347](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:347)
    360         output_structures=self.input.n_output_structures,
[348](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:348)
    361         num_threads=self.server.cores,
[349](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:349)
    362     )
[350](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:350)
    363     for i, structure in enumerate(self._lst_of_struct):
[351](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:351)
    364         with self.project_hdf5.open("output/structures/structure_" + str(i)) as h5:
[352](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:352)

[353](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:353)
File ~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/sqs.py:138, in get_sqs_structures(structure, mole_fractions, weights, objective, iterations, output_structures, num_threads)
[354](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:354)
    136 # preprocess mole-fractions, to print warnings is necessary
[355](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:355)
    137 num_atoms = len(structure)
[356](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:356)
--> 138 composition = mole_fractions_to_composition(mole_fractions, num_atoms)
[357](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:357)
    139 mole_fractions = map_dict(lambda n: n/num_atoms, composition)
[358](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:358)
    141 iterator = ParallelSqsIterator(
[359](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:359)
    142     structure, mole_fractions, weights, num_threads=num_threads
[360](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:360)
    143 )
[361](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:361)

[362](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:362)
File ~/work/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/sqs.py:105, in mole_fractions_to_composition(mole_fractions, num_atoms)
[363](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:363)
     99     warnings.warn(
[364](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:364)
    100         'It is not possible to distribute the species properly. Therefore one "{}" atom was removed. '
[365](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:365)
    101         'This changes the input mole-fraction specification. '
[366](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:366)
    102         '"{}" -> "{}"'.format(removed_species, mole_fractions, map_dict(lambda n: n/num_atoms, composition)))
[367](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:367)
    103 else:
[368](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:368)
    104     # something else is wrong with the mole-fractions input
[369](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:369)
--> 105     raise ValueError('Cannot interpret mole-fraction dict {}'.format(mole_fractions))
[370](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:370)
    107 return composition
[371](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:371)

[372](https://github.com/pyiron/pyiron_atomistics/runs/5625294004?check_suite_focus=true#step:6:372)
ValueError: Cannot interpret mole-fraction dict {'Ni': 0.8, 'Cr': 0.2}
```

**Comment by jan-janssen** [comment]
Also with the latest version the same error message appears. Can this be related to the input parameters being a DataContainer rather than a python dictionary? Maybe @pmrv  can help.

**Comment by dgehringer** [comment]
> The backwards compatibility to 0.0.5 seems to be broken:

That should be fixed. It was caused by a wrong condition

**Review by jan-janssen — APPROVED** [review]
Looks good to me
